### ISSUE TITLE
Readme href 'Create an app with Office 365 APIs' not working

### ISSUE THREAD

**Issue by SaadBinShahid** [OfficeDev/Office-365-AppChrome-Control#17]
README 'Create an app with Office 365 APIs' says 404.

`For more detail guidance, you could check from - Create an app with Office 365 APIs
`

**Comment by lindalu-MSFT** [comment]
@SaadBinShahid This repo covers a feature is no longer supported. We are archiving the repo and it will no longer be maintained. Therefore, I need to close this issue. Thanks,
