### ISSUE TITLE
Use AppChrome-Control in an existing MVC App

### ISSUE THREAD

**Issue by kenneth-y** [OfficeDev/Office-365-AppChrome-Control#18]
Hi,

I would like to know how can I make use of the AppChrome-Control in my existing MVC app which already have authentication/authorization in placed.

I am using IdentityServer4 as my STS (hybrid flow configured to authenticate using Microsoft account). Below is a simple illustration of my mvc app authentication flow.

(MVC App) <--> (IdentityServer4) <--> (Microsoft v2 endpoint)

Appreciate your inputs to put me in the right direction.

**Comment by lindalu-MSFT** [comment]
@kenneth-y This repo covers a feature is no longer supported. We are archiving the repo and it will no longer be maintained. Therefore, I need to close this issue. Thanks,
